#!/bin/bash
echo "=== Testing Intro Video Save ==="
echo ""
echo "✅ Backend validation accepts 'intro' type"
echo "✅ Backend validation accepts 'display_mode', 'must_watch', 'autoplay'"
echo "✅ Frontend uses correct field names"
echo ""
echo "Testing on production: https://prod.qsights.com"
echo ""
echo "Steps to verify:"
echo "1. Go to: https://prod.qsights.com/questionnaires/create"
echo "2. Fill in questionnaire name and program"
echo "3. Add a question"
echo "4. Enable 'Video Intro Block'"
echo "5. Upload a video file"
echo "6. Set display mode to 'Modal'"
echo "7. Check 'Must Watch Before Starting'"
echo "8. Check 'Autoplay'"
echo "9. Click 'Save Questionnaire'"
echo "10. Check the database for the new video metadata"
echo ""
